name: UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Allure
        run: |
          ALLURE_VERSION=2.35.1
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip -O /tmp/allure.zip
          unzip /tmp/allure.zip -d /opt/
          ln -s /opt/allure-${ALLURE_VERSION}/bin/allure /usr/bin/allure

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run UI tests
        run: |
          mkdir -p allure-results
          docker run --rm -v $(pwd)/allure-results:/app/allure-results playwright-tests

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
